/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Glob {
  constructor(pattern: string, options?: JsMatchOptions | undefined | null)
  test(input: string): boolean
  testBuffer(input: Uint8Array): boolean
  testMany(inputs: Array<string>): Array<boolean>
  filter(inputs: Array<string>): Array<string>
  filterIndices(inputs: Array<string>): Array<number>
  get negated(): boolean
}

export declare class GlobSet {
  constructor(patterns: Array<string>, options?: JsMatchOptions | undefined | null)
  test(input: string): boolean
  testBuffer(input: Uint8Array): boolean
  testMany(inputs: Array<string>): Array<boolean>
  matches(input: string): Array<number>
}

export declare function isMatch(input: string, pattern: string, options?: JsMatchOptions | undefined | null): boolean

export declare function isMatchBuffer(input: Uint8Array, pattern: string, options?: JsMatchOptions | undefined | null): boolean

export interface JsMatchOptions {
  dot?: boolean
  nocase?: boolean
  windows?: boolean
  contains?: boolean
  matchBase?: boolean
  nobrace?: boolean
  nobracket?: boolean
  noextglob?: boolean
  noglobstar?: boolean
  nonegate?: boolean
  strictSlashes?: boolean
  maxBraceDepth?: number
  maxLength?: number
}

export interface JsScanResult {
  prefix: string
  base: string
  glob: string
  isBrace: boolean
  isBracket: boolean
  isGlob: boolean
  isExtglob: boolean
  isGlobstar: boolean
  negated: boolean
  negatedExtglob: boolean
}

export declare function makeRe(pattern: string, options?: JsMatchOptions | undefined | null): string

export declare function scan(input: string, options?: JsMatchOptions | undefined | null): JsScanResult
